# Generated by Django 4.0.1 on 2022-01-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receitas_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='pulicada',
            field=models.BooleanField(default=False),
        ),
    ]
