# Generated by Django 4.0.1 on 2022-01-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receitas_pulicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receitas',
            old_name='pulicada',
            new_name='publicada',
        ),
    ]
